# ------ DEPLOYMENTS ------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{NAMESPACE}-deployment"
  labels:
    app: "{NAMESPACE}"
spec:
  selector:
    matchLabels:
      app: "{NAMESPACE}"
  template:
    metadata:
      labels:
        app: "{NAMESPACE}"
        buildNumber: "{BUILD_NUMBER}"
    spec:
      containers:
        - name: "{NAMESPACE}"
          image: asia.gcr.io/eezee-client/{PROJECT_ID}:{DOCKER_IMAGE_TAG}
          imagePullPolicy: Always